namespace: vmware

name: ansible_for_nsxt

version: 1.0.3

readme: README.md

authors:
- Gautam Verma 
- Rahul Raghuvanshi 

description: Ansible Modules for NSX-t

license_file: LICENSE.txt 

tags: [vmware, ansible, nsxt]

dependencies: {}

repository: https://github.com/vmware/ansible-for-nsxt

documentation: https://github.com/vmware/ansible-for-nsxt

homepage: https://github.com/vmware/ansible-for-nsxt

issues: https://github.com/vmware/ansible-for-nsxt/issues

build_ignore: []
